added Chainlink oracles
DjedAlliance/Djed-Solidity pull request #10
Opened 2023-08-15 07:10 UTC by yogesh0509

This is a draft pull request for adding chainlink oracles!!

2023-08-16 07:26 UTC, ceilican requested changes
Thanks, @yogesh0509 ! I left some improvement suggestions.

2023-08-16 07:26 UTC, ceilican commented on src/ChainlinkOracle.sol
> +    uint256 public immutable linkDecimals;
I suggest renaming "link" to "chainlink" everywhere, to make it clearer.

2023-08-16 07:26 UTC, ceilican commented on src/ChainlinkInvertingOracle.sol
> +    uint256 public immutable decimals;
When we say that a number has precision of, let's say, 6 decimals, we mean that we represent a number such as "1.234567" by a numerator "1234567" and a denominator "1000000".

Therefore, it is a bit incorrect and confusing to call the "1000000" number `decimals`.

My suggestion to improve this is: store `6` in `decimals` instead of `1000000` and then use `10 ** decimals` instead of `decimals`.  (See: https://docs.soliditylang.org/en/develop/types.html#exponentiation.)

In a separate PR, could you improve this in the API3 oracle adapters as well?

2023-08-16 07:26 UTC, ceilican commented on src/ChainlinkInvertingOracle.sol
> +        return (decimals * linkDecimals) / uint256(int256(answer));
Note how we are repeatedly computing `decimals * linkDecimals` whenever the `readData` function is called, but this result is always the same since `decimals` and `linkDecimals` are immutable. A more efficient way of doing this would be to have the following line in the constructor:

`scalingFactor = decimals * linkDecimals`

And then to use `scalingFactor` instead of `decimals * linkDecimals` in the `readData` function.

Note that, if we do this, we don't even need to store `decimals` and `linkDecimals` as immutable variables in lines 9 and 10. We can just store `scalingFactor`.

2023-08-16 07:26 UTC, ceilican commented on src/ChainlinkOracle.sol
> +// SPDX-License-Identifier: AEL
My comments in the other oracle apply to this oracle as well.

I think they also apply to the API3 oracles too. Therefore, if you could create a separate PR improving the API3 oracles too, it would be great.

2023-08-16 07:26 UTC, ceilican commented on scripts/deployChainlinkOracle.sh
> +forge create --legacy --rpc-url ${RPC_URL} \
Could you add an example ".env" file in an "env" folder in the root of this repo?  Of course, do *not* add your private in the example file.

2023-08-21 06:45 UTC, yogesh0509 commented on src/ChainlinkInvertingOracle.sol
> +    uint256 public immutable decimals;
Sure!!
For chainlink oracles, we need not store the decimal places. Rather chainlink itself provides a function `decimals()` to get the number of decimal places in the response. So instead of storing `chainlinkDecimals`, should we just use the `decimals()` function inside our `readData()` function and not store chainlinkDecimals at all? Also, we need not provide `chainlinkDecimals` in the constructor.

2023-08-21 07:10 UTC, yogesh0509 commented on scripts/deployChainlinkOracle.sh
> +forge create --legacy --rpc-url ${RPC_URL} \
what should be the precision of `DJED_DECIMALS` in the `example.env` file.

2023-08-21 08:29 UTC, ceilican commented on src/ChainlinkInvertingOracle.sol
> +    uint256 public immutable decimals;
Yes. Calling the `decimals()` function, as you suggested, is even better! Let's go ahead with this idea.

2023-08-21 18:20 UTC, yogesh0509 commented on src/ChainlinkInvertingOracle.sol
> +    uint256 public immutable decimals;
I have pushed the updated code after improving upon this idea

2023-08-21 18:21 UTC, yogesh0509 commented on src/ChainlinkOracle.sol
> +// SPDX-License-Identifier: AEL
Sure I would create a separate PR for api3 oracles after this PR is merged.

2023-08-22 06:17 UTC, ceilican requested changes

2023-08-22 06:17 UTC, ceilican commented on src/ChainlinkInvertingOracle.sol
> +        scalingFactor = (uint256(dataFeed.decimals())) * _decimals;
Here is an additional optimization:

`scalingFactor = 10 ** (uint256(dataFeed.decimals())) * _decimals;`

Then, in lines 23 and 24, you can just use `scalingFactor` instead of `10 ** scalingFactor`.

2023-08-22 06:17 UTC, ceilican commented on src/ChainlinkInvertingOracle.sol
> +        require((uint256(int256(answer))) < (10 ** scalingFactor), "value returned has higher precision");
Why do we need this line? Could you explain with a concrete example?

2023-08-22 06:17 UTC, ceilican commented on src/ChainlinkOracle.sol
> +        uint8 chainlinkDecimals = dataFeed.decimals();
Optimize this file too, by moving this line to the constructor and storing a `scalingFactor`, as you did for `ChainlinkInvertingOracle`.

2023-08-22 06:25 UTC, ceilican commented on scripts/deployChainlinkOracle.sh
> +forge create --legacy --rpc-url ${RPC_URL} \
18

2023-08-22 06:34 UTC, yogesh0509 commented on src/ChainlinkOracle.sol
> +        uint8 chainlinkDecimals = dataFeed.decimals();
The variable `chainlinkDecimals` is not used anywhere but in the `readData()` function. Thus, we need not store it in storage by defining it in the constructor. When a variable is defined in the function itself it is stored in memory. 
And storage in "memory" is much cheaper when compared to storing in "storage".
This way we could save some gas. How do you think we should proceed?

2023-08-22 07:01 UTC, ceilican commented on src/ChainlinkOracle.sol
> +        uint8 chainlinkDecimals = dataFeed.decimals();
Note that:

* calling `dataFeed.decimals()` also has a gas cost and this gas cost is incurred every time `readData()` is called. Over time, the cost of calling `dataFeed.decimals()` over and over again will be much higher than the cost of calling it only once in the constructor and storing the data in storage.

* I am not suggesting that we store `chainlinkDecimals` in storage, but rather that we store `scalingFactor` instead of `chainlinkDecimals` and `decimals` in storage, as you have already done in the other oracle adapter. Therefore, there will be no increase in storage costs, because `decimals` will be eliminated and `scalingFactor` will be added.

> How do you think we should proceed?

For the reasons explained above, we should do on this oracle exactly what was done in `ChainlinkInvertingOracle` with the `scalingFactor`.

2023-08-23 05:00 UTC, yogesh0509 commented on src/ChainlinkInvertingOracle.sol
> +        require((uint256(int256(answer))) < (10 ** scalingFactor), "value returned has higher precision");
This line is required to avoid the returned value being equal to `0`. Suppose the value `answer` returned by the price oracle is greater than the `scalingFactor`, then our returned value will be `(scalingFactor) / uint256(int256(answer))`.

Now if `answer > scalingFactor`, our price oracle will return value `0` even if the `answer` is not zero but a very high number.

2023-08-24 06:28 UTC, ceilican requested changes

2023-08-24 06:28 UTC, ceilican commented on src/ChainlinkInvertingOracle.sol
> +        scalingFactor = 10 ** (uint256(dataFeed.decimals())) * _decimals;
I think there is a bug here. The "*" should be a "+" or "-". Shouldn't it?

2023-08-24 06:39 UTC, ceilican commented on src/ChainlinkInvertingOracle.sol
> +        require((uint256(int256(answer))) < (10 ** scalingFactor), "value returned has higher precision");
But look:

Let's suppose that our scaling factor is `1000`. This means that we are only interested in the first 4 decimal digits of the result. 

Let's suppose that the `XYZ/USD` price is `10000`.  (So, `answer > scalingFactor`.) 
When we invert this, we get a `USD/XYZ` price of `0.00001`.

Because we are only interested in the first 4 decimal digits, the correct behavior in this case should be to return a `USD/XYZ` price of `0.0000`.  Throwing an exception and returning nothing because `answer > scalingFactor` is an incorrect behavior.

There is nothing wrong with a price of `0`. When `answer > scalingFactor`, the price will in fact be `0` within the desired precision. So, that's the correct answer.

Therefore, we must remove that `require` statement from the code.

2023-08-24 14:31 UTC, yogesh0509 commented on src/ChainlinkInvertingOracle.sol
> +        require((uint256(int256(answer))) < (10 ** scalingFactor), "value returned has higher precision");
Should I make the same changes in api3 oracle as well?

2023-08-24 16:29 UTC, ceilican commented on src/ChainlinkInvertingOracle.sol
> +        require((uint256(int256(answer))) < (10 ** scalingFactor), "value returned has higher precision");
Yes.

2023-08-24 16:38 UTC, ceilican requested changes

2023-08-24 16:38 UTC, ceilican commented on src/ChainlinkInvertingOracle.sol
> +
Remove this white line.

2023-08-24 16:38 UTC, ceilican commented on src/ChainlinkInvertingOracle.sol
> +        require(answer >= 0, "Cannot convert negative value");
Will `answer` ever be negative? A price is always positive. So, even if a dataFeed could normally provide negative answers, a dataFeed that is providing price data will never provide a negative answer.

Also, I think this line is redundant, because the explicit conversion in line 23 would revert anyway if `answer` is negative. But please check this in Solidity's documentation. I'm not 100% sure.

2023-08-24 16:38 UTC, ceilican commented on src/ChainlinkOracle.sol
> +
Remove this white line.

2023-08-24 16:41 UTC, ceilican commented on src/ChainlinkInvertingOracle.sol
> +        require(answer >= 0, "Cannot convert negative value");
Ah, I have just checked (https://docs.soliditylang.org/en/develop/types.html#explicit-conversions) and the explicit conversion will *not* revert...

2023-08-24 16:41 UTC, ceilican commented on src/ChainlinkInvertingOracle.sol
> +        require(answer >= 0, "Cannot convert negative value");
Still, due to first reason above, I still think we can remove this `require`.

2023-10-10 09:52 UTC, ceilican approved these changes

2023-10-10 09:55 UTC, ceilican commented
@yogesh0509 , this PR is ready to be merged, but i cannot merge it because it is tagged as a "draft". Could you remove the "Draft" status from it?

2023-10-10 09:58 UTC, merged