sepolia testnet deployments
DjedAlliance/Djed-Solidity pull request #16
Opened 2023-12-28 18:50 UTC by yogesh0509

Added deploy scripts for `djed` deployment on `sepolia testnet` using chainlink oracle.

2023-12-29 09:58 UTC, ceilican requested changes

2023-12-29 09:58 UTC, ceilican commented on scripts/Helper.sol
> +    uint256 constant public DJED_DECIMALS = 6;
The values of all these constants will depend on the network. Therefore, they should not be hard-coded in this Helper script.

2023-12-29 09:58 UTC, ceilican commented on scripts/Helper.sol
> +    uint256 constant public DJED_DECIMALS = 6;
One way to deal with this would be to read the values of these constants from the env file, but this is also a bit inconvenient, now that we are using foundry scripts.

I have been thinking how we could better structure this. I will suggest some ideas in my other comments.

2023-12-29 09:58 UTC, ceilican commented on scripts/Helper.sol
> +            address treasuryAddress
i think this function should return all the constants.

2023-12-29 09:58 UTC, ceilican commented on scripts/Helper.sol
> +
For each network, we could create a separate file with a `Constants` contract containing the constant values. For example, for Sepolia, we could create `SepoliaConstants.sol`, which would look like this:

```
contract Constants {
       // ...
     uint256 constant public RESERVE_COIN_INITIAL_PRICE=100000000000000000000;
    uint256 constant public TX_LIMIT=10000000000;
     // ...
}
```

And there would be a similar `MilkomedaTestnetConstants.sol` file and so on...

2023-12-29 09:58 UTC, ceilican commented on scripts/Helper.sol
> +        if (network == SupportedNetworks.ETHEREUM_SEPOLIA) {
Then, here, we just write something like this:

```

Constants constants;

if (network == SupportedNetworks.SEPOLIA) {
   constants = new SepoliaConstants();
}  else if (network == SupportedNetworks.MILKOMEDA_TESTNET) {
   constants = new MilkomedaTestnetConstants();
}

return (constants.chainlinkOracle, constants.chainlinkDataFeed, constants.treasuryAddress, ..., constants.reservecoinsInitialPrice, ...)
```

2024-01-11 10:49 UTC, ceilican requested changes
The code is good, @yogesh0509 ! Before merging, could you add a section in the README explaining how to deploy using the new scripts?

2024-01-11 14:14 UTC, yogesh0509 commented
> The code is good, @yogesh0509 ! Before merging, could you add a section in the README explaining how to deploy using the new scripts?

sure!!

2024-01-16 16:42 UTC, merged