Shu oracle
DjedAlliance/Djed-Solidity pull request #27
Opened 2024-05-22 00:07 UTC by yogesh0509

@ceilican can you look at these tests and let me know if we are covering all cases. I think there might be some scenarios where our ShuOracleConverter might give incorrect values

2024-05-29 17:56 UTC, ceilican requested changes

2024-05-29 17:56 UTC, ceilican commented on src/IOracleShu.sol
> +    function readMaxPrice() external view returns (uint256, uint256);
Please add a comment explaining what the return values are.

2024-05-29 17:56 UTC, ceilican commented on src/ShuOracleConverter.sol
> +    uint256 public contractDeploymentTime;
Why do we need this?

2024-05-29 17:56 UTC, ceilican commented on src/ShuOracleConverter.sol
> +    uint256 public contractDeploymentTime;
I see... You use it in line 55.

But, if we remove it and do only "`currentTime / (1 hours))`" in line 55, I think the only thing that will happen is that the first hour interval will be shorter than 1 hour. This would be fine and would simplify the code and reduce gas.  

Could you check this and, if my thinking above is indeed correct, remove this variable from the code?

If we were to keep, it should be declared as immutable.

2024-05-29 17:56 UTC, ceilican commented on src/test/ShuOracleConverter.t.sol
> +    function test_updatePrice() public {
We need more tests...  We should test what happens if we skip more than 24 hours, and also what happens when we skip, for intance, 2.5 hours, 0.3 hours...

2024-05-29 17:56 UTC, ceilican commented on src/ShuOracleConverter.sol
> +        }
The else case is missing.

2024-05-29 17:56 UTC, ceilican commented on src/ShuOracleConverter.sol
> +                ((currentTime - contractDeploymentTime) / (1 hours)) %
Suppose that `T2 = T1 + 24 hours`.

Then this function will return the same value when applied to `T1` or `T2`. In other words, `_getHourDifference(T1) == _getHourDifference(T2)`.

Consequently, `updateOracleValues` will have the same effect when called on `T1` and on `T2`. But this should **not** be the case.

Therefore, there must be a bug here.

2024-05-29 17:56 UTC, ceilican commented on src/ShuOracleConverter.sol
> +                ((currentTime - contractDeploymentTime) / (1 hours)) %
Also, I think this function is returning the time difference not in hours, but in seconds, because we are not dividing by 3600.

2024-06-04 05:08 UTC, yogesh0509 commented on src/ShuOracleConverter.sol
> +    uint256 public contractDeploymentTime;
Yes, I think we can remove this variable. The only tradeoff will be the first hour being shorter.

2024-06-04 05:10 UTC, yogesh0509 commented on src/ShuOracleConverter.sol
> +        }
There is no need for a else case here.

2024-06-04 05:25 UTC, yogesh0509 commented on src/ShuOracleConverter.sol
> +                ((currentTime - contractDeploymentTime) / (1 hours)) %
> Suppose that `T2 = T1 + 24 hours`.
> 
> Then this function will return the same value when applied to `T1` or `T2`. In other words, `_getHourDifference(T1) == _getHourDifference(T2)`.
> 
> Consequently, `updateOracleValues` will have the same effect when called on `T1` and on `T2`. But this should **not** be the case.
> 
> Therefore, there must be a bug here.

Yes, this is an error. I will think of another way to determine if time has passed.



> Also, I think this function is returning the time difference not in hours, but in seconds, because we are not dividing by 3600.

When divided by 1 hours, it is automatically converted from seconds to hours.

2024-06-11 17:37 UTC, ceilican commented on src/ShuOracleConverter.sol
> +    uint256 public contractDeploymentTime;
Yes, it is fine for the first hour to be shorter.

2024-06-11 17:40 UTC, ceilican commented on src/ShuOracleConverter.sol
> +                ((currentTime - contractDeploymentTime) / (1 hours)) %
> Yes, this is an error. I will think of another way to determine if time has passed.

OK. If you need help, please let me know.

2024-06-11 17:47 UTC, ceilican commented on src/ShuOracleConverter.sol
> +        }
We do need an else case. 

Let's suppose that all the previously stored prices are equal to `5` and thus `_currentMinPrice == 5` and `_currentMaxPrice == 5`.  Then suppose that `currentHour == previousHour` and `oracle.readData()` returns `7`. In such a case, we will need to update the stored prices for the current hour and the current maximum price.

2024-06-21 09:28 UTC, yogesh0509 commented on src/ShuOracleConverter.sol
> +        }
Great point, do you think we can handle this case if we move lines 40-44 out of the if block.

2024-06-25 01:56 UTC, ceilican commented on src/ShuOracleConverter.sol
> +    function _calculateMinPrice() internal {
Rename this to "_updateMinPrice".

"Update makes it clear that the function has a side-effect, whereas "calculate" misleadingly suggests otherwise.

2024-06-25 01:56 UTC, ceilican commented on src/ShuOracleConverter.sol
> +        return uint8((currentTime / (1 hours)) % 24);
The `% 24` is very strange, and it is a strong indicator to me that there is probable something wrong in this code.

It is improbable that a code that gives the same result independently of whether the hour diference is, let's say, 1 or 25 is working correctly.

Could you please think carefully about this?

2024-06-25 02:18 UTC, ceilican requested changes

2024-06-25 02:18 UTC, ceilican commented on src/DjedShu.sol
> +    function ratio() external view returns (uint256) {
I think we need two `ratio` functions: one that uses the max price and one that uses the min price.

2024-06-25 02:18 UTC, ceilican commented on src/DjedShu.sol
> +        uint256 sSC = stableCoin.totalSupply();
Lines 197--200 and 205--208 are identical. Please think how to eliminate this code duplication.

2024-06-25 02:18 UTC, ceilican commented on src/DjedShu.sol
> +        uint256 value = (amountSC * scP) / scDecimalScalingFactor + (amountRC * rcTargetPrice(scP, 0)) / rcDecimalScalingFactor;
When selling RCs, we should use the scMaxPrice. Therefore, the argument to `rcTargetPrice` should not be `scP`.

2024-06-25 02:18 UTC, ceilican commented on src/DjedShu.sol
> +        uint256 scP = scMinPrice(0);
scMaxPrice

2024-06-25 02:18 UTC, ceilican commented on src/DjedShu.sol
> +        uint256 scP = scMaxPrice(msg.value);
scMinPrice.

Try to understand why it should be scMinPrice instead of scMaxPrice.

2024-07-11 14:45 UTC, ceilican commented on src/ShuOracleConverter.sol
> +    function _getcurrentHour(uint256 currentTime)
"c" => "C"

2024-07-16 12:07 UTC, ceilican requested changes

2024-07-16 13:19 UTC, yogesh0509 commented on src/ShuOracleConverter.sol
> +    uint8 public constant UPDATE_TIME_IN_HOUR = 24;
Then we can't set movingPrice as a fixed sized array of 24 as we need to fix the size while declaring the variable.

2024-07-16 13:21 UTC, yogesh0509 commented on src/ShuOracleConverter.sol
> +        _minIndex = previousHour;
only if the previousHour is 0

2024-07-16 13:29 UTC, yogesh0509 commented on src/ShuOracleConverter.sol
> +    uint256 private iterations = 0;
how about `_iterationsPerHour`?

2024-07-17 08:31 UTC, ceilican commented on src/ShuOracleConverter.sol
> +    uint256 private iterations = 0;
maybe `updatesSinceHourStart`?

2024-07-17 08:37 UTC, ceilican commented on src/ShuOracleConverter.sol
> +    uint8 public constant UPDATE_TIME_IN_HOUR = 24;
Ah, OK. That's unfortunate. Let's keep it as a constant then.

By the way, the name of this variable could be improved too. Maybe `NUMBER_OF_PAST_HOURS`?

2024-07-17 08:40 UTC, ceilican commented on src/ShuOracleConverter.sol
> +        previousHour = uint8(
But, since we will be initializing the entire `movingPrice` array with `latestPrice`, does it matter to which point in time we initialize `previousHour`?

2024-07-17 08:44 UTC, ceilican commented on src/ShuOracleConverter.sol
> +        previousHour = uint8(
Here is another perspective:

`previousHour` should store the hour of the last oracle read. During initialization, the has been no previous oracle read. We can pretend that there was a previous oracle read at an arbitrary hour and that its price was exactly `latestPrice` as well. Because this hour of this "fake oracle read" can be arbitrary, it doesn't matter if it is set to `0` or to `(block.timestamp / (1 hours)) % UPDATE_TIME_IN_HOUR`. Setting it to `0` would be cheaper (since variables are initialized to zero by default) and would save 3 lines of code.

2024-07-17 08:45 UTC, ceilican commented on src/ShuOracleConverter.sol
> +        previousHour = uint8(
Or am I missing something?

2024-07-17 08:45 UTC, ceilican commented on src/ShuOracleConverter.sol
> +        _minIndex = previousHour;
See my previous remarks. I think we can initialize `previousHour` to zero.

2024-07-17 08:57 UTC, yogesh0509 commented on src/ShuOracleConverter.sol
> +    uint256 private iterations = 0;
> how about `_iterationsPerHour` or `_updatesPerHour`?

Okay, I keep an '_' at the beginning of any private variable name. Is it fine or should I remove these?

2024-07-17 08:58 UTC, yogesh0509 commented on src/ShuOracleConverter.sol
> +    uint8 public constant UPDATE_TIME_IN_HOUR = 24;
Yes Initializing these in the constructor is definitely preferred but I could not find any alternatives.

2024-07-17 14:55 UTC, yogesh0509 commented on src/ShuOracleConverter.sol
> +        previousHour = uint8(
There could be a potential bug with this approach. Let us assume that initially `previousHour` is equal to 0 but it's actual value should be 22 based on our calculation `(block.timestamp / (1 hours)) % UPDATE_TIME_IN_HOUR` .  Now if two hours have passed and `updateOracleValues` is called, even though we should enter the if condition `if(currentHour != previousHour)`, it will not thus not updating latest prices as it should.

2024-07-17 15:16 UTC, ceilican commented on src/ShuOracleConverter.sol
> +    uint256 private iterations = 0;
It is up to you. Just be consistent with the style conventions that you choose to follow.

2024-07-17 15:17 UTC, ceilican commented on src/ShuOracleConverter.sol
> +        previousHour = uint8(
OK. You convinced me.

2024-07-17 15:23 UTC, ceilican commented on src/ShuOracleConverter.sol
> +        previousHour = uint8(
But wait a moment. What if the actual value is `0` and then now 24h have passed and `updateOracleValues` is called. Wouldn't the bug you described also occur??

It seems that the bug you described is a more general problem related to not handling the conditionals properly when there is a 24h difference between `currentHour` and `previousHour`... and not related to the initialization of `previousHour`.

Could you think about this very carefully? It could be a critical bug.

2024-07-18 13:31 UTC, yogesh0509 commented on src/ShuOracleConverter.sol
> +        previousHour = uint8(
This change should solve the bug, I think 
`currentHour != previousHour || (lastTimestamp + 1 days) == block.timestamp`.
Do you think we can modify anything else with a similar logic to also remove lines 25-27?

2024-07-19 05:32 UTC, ceilican commented on src/ShuOracleConverter.sol
> +        previousHour = uint8(
Maybe. Could you push a commit with this change? I need to see the whole code to understand the consequences.

2024-07-19 12:19 UTC, ceilican requested changes

2024-07-19 12:19 UTC, ceilican commented on src/ShuOracleConverter.sol
> +                    (previousHour + i) % UPDATE_TIME_IN_HOUR
This is very clever! Very smart! But it means that we are making a modulo operation in every iteration of the loop. Replacing this loop, by two loops, one going from previousHour until the end of the array or currentHour, whatever is smaller, and the other, if necessary, going from the beginning of the array until currentHour would be more gas efficient. Check how much gas we could save, to see if it would be worth optimizing this.

2024-07-19 12:19 UTC, ceilican commented on src/ShuOracleConverter.sol
> +            (lastTimestamp + 1 days) == block.timestamp
It could be 2 days, or 3 days, or 4 days... This code will only work for 1 day.

Here is a much simpler condition:

`if (block.timestamp / (1 hours) - previousHour >= 1)`

2024-07-19 12:19 UTC, ceilican commented on src/ShuOracleConverter.sol
> +            (lastTimestamp + 1 days) == block.timestamp
Please double check whether my suggested simpler condition works as intended.

2024-07-19 19:46 UTC, yogesh0509 commented on src/ShuOracleConverter.sol
> +            (lastTimestamp + 1 days) == block.timestamp
yes, this works

2024-07-19 19:59 UTC, yogesh0509 commented on src/ShuOracleConverter.sol
> +                    (previousHour + i) % UPDATE_TIME_IN_HOUR
The gas optimization is very small but can be considered over a longer period of time, turns out simpler approach is actually the better one シ.

Here are gas comparisons for the three test cases:

#### CURRENT APPROACH
```
// test_updateOracleValues_daysPassed() (gas: 291754)
// test_updateOracleValues_multipleHours() (gas: 257032)
// test_updateOracleValues_noTimeElapsed() (gas: 61980)
```

#### TWO LOOPS
```
// test_updateOracleValues_daysPassed() (gas: 281183)
// test_updateOracleValues_multipleHours() (gas: 249531)
// test_updateOracleValues_noTimeElapsed() (gas: 61980)
```

2024-07-22 12:00 UTC, ceilican commented on src/ShuOracleConverter.sol
> +                    (previousHour + i) % UPDATE_TIME_IN_HOUR
OK. The differences are insignificant. Let's keep the current approach then.

2024-08-07 10:25 UTC, ceilican requested changes

2024-08-07 10:25 UTC, ceilican commented on src/ShuOracleConverter.sol
> +            block.timestamp / (1 hours) - previousHour >= 1
I think that `currentHour != previousHour || block.timestamp / (1 hours) - previousHour >= 1` is equivalent to `block.timestamp / (1 hours) - previousHour >= 1`. If I am right, the former could be replaced by the latter.

Could you check this carefully and, if I am right, do this replacement?

2024-09-21 04:19 UTC, ceilican approved these changes

2025-03-10 16:24 UTC, ceilican approved these changes

2025-03-10 16:24 UTC, merged