added Api3 oracle
DjedAlliance/Djed-Solidity pull request #9
Opened 2023-06-22 21:51 UTC by yogesh0509

This is a work-in-progress pull request!!

I have added a proxy contract that reads values from dAPI that have already been deployed on various chains. A list of all the smart contract addresses that have already been deployed on different chains can be found on [API3 market](https://market.api3.org/)

2023-06-23 07:14 UTC, ceilican requested changes
Perfect, @yogesh0509 .

I think the only things that are missing are:

1 - a deployment script in the `/scripts` folder.

2 - a markdown file (in a `/docs` folder) explaning where to find the proxy address, linking to the AP3 martplace, and already listing some example proxy addresses.

2023-06-23 07:14 UTC, ceilican commented on src/API3Oracle.sol
> +    function acceptTermsOfService() external{}
Could you add a space between "l" and "{" here?

2023-06-23 07:27 UTC, ceilican commented
Ah, @yogesh0509 , here is another challenge to keep in mind and address:

Those API3 proxy oracles may provide data with a different number of decimal digits than what we would like to use in Djed. Therefore, I think we need to have 3 additional arguments in the constructor: one for the number of decimal digits from the data that we are reading from API3 and one for the number of decimal digits for the data we will be providing to Djed. Then we will need to convert `value` to desired number in our `readData` function.

2023-06-23 07:31 UTC, ceilican commented
@yogesh0509 , also, it may be the case that we need, for instance, "USD/MATIC" instead of "MATIC/USD". If this is the case, then I suggest creating a separate contract called `API3InvertingOracle` that would be identical to `API3Oracle` except that it would return `1/value` instead of `value`.

2023-07-06 06:52 UTC, ceilican reviewed
Please use camelCase for all variable names.

The variables in lines 7--9 are set by the constructor and then are never changed. Therefore, you can declare them as `immutable`. Doing so has many advantages (that you can learn about by reading Solidity's documentation).

2023-07-06 06:52 UTC, ceilican commented on src/API3InvertingOracle.sol
> +        require((uint256(int256(value))) < (DJED_DECIMALS / ADDITIONAL_DECIMALS_PRECISION), "value returned has higher precision");
It is not clear to me why this is needed. Could you explain with an example?

2023-07-06 06:57 UTC, ceilican commented on src/API3Oracle.sol
> +    uint256 public DJED_DECIMALS;
Rename this variable to just `decimals`.

The oracle may be used by other projects besides Djed. Therefore, we shouldn't have "Djed" appearing in the names of any oracle variables.

2023-07-06 07:11 UTC, ceilican requested changes

2023-07-06 07:11 UTC, ceilican commented on src/API3Oracle.sol
> +        ADDITIONAL_DECIMALS_PRECISION = _djed_DECIMALS / _api3_DECIMALS;
It would be better to store api3Decimals instead...

2023-07-06 07:11 UTC, ceilican commented on src/API3Oracle.sol
> +        return (uint256(int256(value)) * ADDITIONAL_DECIMALS_PRECISION) / DJED_DECIMALS;
... and then here replace `* ADDITIONAL_DECIMALS_PRECISION) / DJED_DECIMALS` by simply `/ api3Decimals`, since `ADDITIONAL_DECIMALS_PRECISION` is equal to `DJED_DECIMALS / api3Decimals`.

2023-07-06 07:11 UTC, ceilican commented on src/API3Oracle.sol
> +        return (uint256(int256(value)) * ADDITIONAL_DECIMALS_PRECISION) / DJED_DECIMALS;
Once you do this simplification, you realize that the conversion in this line is probably wrong.

I think it should be `(uint256(int256(value)) * DJED_DECIMALS / api3Decimals`.

Could you please check?

2023-07-06 07:11 UTC, ceilican commented on src/API3Oracle.sol
> +        return (uint256(int256(value)) * ADDITIONAL_DECIMALS_PRECISION) / DJED_DECIMALS;
For example:

Suppose that the price is `2.534`, API3 uses 6 decimals and our oracle should return a result with 4 decimals.

This means that we will read 2534000 from API3 and we should return 25340.

So, `DJED_DECIMALS` should be equal to `10000` and `api3Decimals` should be equal to `1000000`. And to to transform 2534000 to 25340, we should multiply by `DJED_DECIMALS` and divide by `api3Decimals`.

2023-07-10 20:02 UTC, yogesh0509 commented on src/API3Oracle.sol
> +    uint256 public DJED_DECIMALS;
we can chose not to store `DJED_DECIMALS` at all as we don't need it further for any conversions.

2023-07-10 20:54 UTC, yogesh0509 commented on src/API3InvertingOracle.sol
> +        require((uint256(int256(value))) < (DJED_DECIMALS / ADDITIONAL_DECIMALS_PRECISION), "value returned has higher precision");
This is so that the numerator is always greater than the denominator. If the value returned by api3 is very high denominator can be greater than the numerator in which case the returned value will be 0. 
Although in this push the logic is a bit flawed which I have corrected in the latest push.

2023-07-17 07:12 UTC, ceilican approved these changes

2023-07-17 07:13 UTC, merged